# -*- coding: utf-8 -*-
"""EXP 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9k_yUVBBEtAZzrR2hL1-XSmwS0Vxl-q

EXP 1
"""

arr = [10, 25, 30, 45, 50]
key = 30

for i in range(len(arr)):
    if arr[i] == key:
        print("Key found at index", i)
        break
else:
    print("Key not found")